---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
skip-files:
  - ./code_examples/3-Structured_Problem_Solving/4-Scope_of_Variables/Go/*.go
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - text: 'shadow: declaration of "variableX" shadows declaration at'
      linters: [govet]

linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    # - govet
    - revive
  disable:
    - govet
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: 
    #   `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: false
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true